services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080

  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - 5000:5000

volumes:
  db:
    driver: local
  pgadmin:
    driver: local